### ISSUE TITLE
Phong blending across multiple bmodels

### ISSUE THREAD

**Issue by bstordeur** [ericwa/ericw-tools#292]
Phong usually transitions well across different things, like func_detail and func_group, and it also works well on single bmodels like func_wall, but it doesn't transition smoothly across multiple func_walls. Obviously I have no idea if this is actually fixable! :D 

Example : 
![image](https://user-images.githubusercontent.com/5883104/75604888-b047f700-5add-11ea-99fa-5b9f4214ca21.png)
![image](https://user-images.githubusercontent.com/5883104/75604916-f4d39280-5add-11ea-8252-33036d7ae7e1.png)
- On the left, a pillar func_wall, just one brush, phong works nicely.
- In the middle, a pillar made up of multiple individual func_walls to form the whole shape, phong breaks here.
- On the right, same as the middle one, except all the brushes have been combined into one func_wall, phong works again.

Here's the map (renamed to .txt so github doesn't complain) : 
[testfuncphong.txt](https://github.com/ericwa/ericw-tools/files/4270121/testfuncphong.txt)

This is a pretty borderline cases, but I've had it happen a few times as I try to fake blending of curved surfaces with varying alpha values, which require me to make individual func ents. For example this waterfall that blends seamlessly (apart from the Phong issues) into the water : 
![blendfall](https://user-images.githubusercontent.com/5883104/75604930-22204080-5ade-11ea-9cb9-d7b218777e99.gif)

**Comment by ericwa** [comment]
It's probably not practical because models are compiled independently by qbsp, so there's no guarantee the vertices will line up. I could try something where you specify something like "_smooth_across_models" "uniqueID" on all of the bmodels and if you are lucky and qbsp created vertices that line up between the models, it'll work.. but there's not much you can do to influence qbsp, so I feel it'll just be a headache
