### ISSUE TITLE
Can't crouch.

### ISSUE THREAD

**Issue by KleskBY** [ericwa/ericw-tools#306]
I am using QC setsize function to change player size. When I play on CS 1.6 or old quake maps, I can crouch and get into small holes (like vents). I understand that the crouch feature doesn't exist in vanilla Quake, but I am trying to understand why this happens and how to fix this. Thank you.

**Comment by ericwa** [comment]
This is the precomputed collision hulls trick Quake uses. Every .bsp has 3 copies of the map in it, hull0 is the one you see, and hull1 and hull2 are just used for collision (hull1 = player sized, and  hull2 = shambler sized) and have all of the brushes expanded so the engine can do point and line segment tests rather than Box/BSP tests and Box/BSP sweeps. As a downside of this, it means the possible bounding box sizes are limited to point, player sized, or shambler sized, since they're baked in the .bsp file.

So if you call `setsize`, the entity will still collide against the world as if it's a player or shambler size. But it will use the newly requested size for collisions against other entities.

**Comment by KleskBY** [comment]
Thank you for explaining.

**Comment by KleskBY** [comment]
@ericwa If you have time. Can you please tell me were I can edit player sizes or I cant?
