### ISSUE TITLE
Feature Idea: _addLight on brushes like func_group, func_detail, etc.

### ISSUE THREAD

**Issue by nathnolt** [ericwa/ericw-tools#340]
## Question about how _minlight works exactly
_minlight sets the light to a brush to a minimum. I'm not sure if a point light makes it brighter, in the same way that it would make a non _minlight brush brighter, or if it would make the non minlighted brush as light as the the _minlight brush, without the _minlighted brush becoming brighter. As in: let's say that func_group1 had a _minlight of 200, and that another func_group right next to it didn't have this. And there also is a point light entity lighting up both. Does it make both brighter?

## Why
Having something like _addLight would be as if there was a point light of the _addLight value which only applied to that brush, but _addLight would be applied on the entire brush.

## Negative value
If supplied a negative value, it would subtract light I guess.

**Comment by Paril** [comment]
_minlight is only a minimum; if it's set to 10, then any luxels below 10 brightness will be set to 10 (scaled by the minlight color). Anything above that can still exist as-is. With a minlight of 200 you'd need a pretty bright light to light it up.

The suggestion of _addlight would just end up being the same as having a higher _minlight value, since it's effectively just doing `min(minlight, value + addlight)`; the same result could be reached mathematically by just adding your addlight value to minlight (`min(minlight + addlight, value)`)

**Comment by ericwa** [comment]
We do actually have an additive minlight feature inherited from tyrutils, if you use `-addmin` flag / `_addmin 1` in worldspawn, the minlight formula changes from `value = max(value, minlight);` to `value += minlight;`. That affects all uses of minlight across the level though.

It's kind of a niche feature, but we could expose at a per-func_group/per-bmodel level if there's interest. I'd probably lean towards that over adding `_addLight` since it would be using an existing /feature.

What also might be relevant, is we've added a light channel masking feature in the dev builds. It lets you selectively make lights affect only certain models. Currently undocumented, but the docs would look something like:

> light entity keys:
> 
> - `_light_channel_mask` - this light only affects bmodels with at least 1 bit matching in their `_object_channel_mask`
> - `_shadow_channel_mask` - this light only gets blocked by bmodels with at least one bit of their 
>   `_object_channel_mask` matching this mask. Defaults to `_light_channel_mask` if unset.
> 
> bmodel key:
> 
> - `_object_channel_mask` - only receive lighting from lights whose `_light_channel_mask` matches at least one bit of this mask

**Comment by nathnolt** [comment]
Wow, thanks for the great responses. 
The _addmin 1 seems to do exactly what I want and is very cool.  It even works with negative values on the light entities.

Doing _addmin per brush makes more sense than _addLight, since it's already a thing.  But the global one on worldspawn is already great. I don't know how hard it would be to add it per bmodel / func_group / func_detail*

I wish the new versions of this tool were a bit more accessible, because right now you get the documentation for the old versions, and the downloads for the old version. 
Maybe the readme could be updated to link to the download page for the new versions.

---

Alright, I figured out `_light_channel_mask` and `_object_channel_mask` Initially I tried a value of 1 but nothing was happening. They seem to work well for the bmodel entities ( real non compiler func_* entities ).

Sadly, this does not work with func_group or func_detail*. I wish it would & don't know if it's possible.

Thanks again.

**Comment by Paril** [comment]
It should work on group/detail. Note that 1 is the main world lighting, so you'd only use bits 2 and above for additional lighting stuff.

**Comment by ericwa** [comment]
I didn't implement the mask stuff for func_group/detail yet (so currently they're hardcoded to have `_object_channel_mask 1`), but that's planned.

>  Maybe the readme could be updated to link to the download page for the new versions.

Good idea!

**Comment by nathnolt** [comment]
I think this can be closed?

**Comment by ericwa** [comment]
The `_object_channel_mask` was implement on func_group/detail in the meantime.
