### ISSUE TITLE
Sky brushes should not have outside faces

### ISSUE THREAD

**Issue by hemebond** [ericwa/ericw-tools#359]
Currently the tools will create all faces for a sky brush, even if that face is only exposed to the void. This means with some engines, when noclipped outside the level, I can't see into the level because the outside sky brush face blocks the view.

**Comment by Paril** [comment]
Sky brushes are just solids, so it shouldn't create outside faces. I haven't seen this in the dev builds, at least.

**Comment by ericwa** [comment]
Sky is a separate content type in Q1, it's similar to solid though (seals map, etc.)

This is working correctly at least for a minimal box map. (It's sealed, I just hid one side of the box for screenshot:)

![image](https://github.com/ericwa/ericw-tools/assets/239161/9231eed2-792d-406f-91a9-234c54ed2740)

We have a unit test `simple_worldspawn_sky` that checks that the bsp->dfaces array only contains 1 sky face.

@hemebond any ideas how to repro the issue?

**Comment by hemebond** [comment]
@ericwa It actually looks like perhaps this engine (FTEQW) is rendering the *back*-face of the sky faces, so I've gone back to the devs to check.

![image](https://github.com/ericwa/ericw-tools/assets/424218/3bca59e1-0482-4de8-b143-11956d5b0c4f)

**Comment by hemebond** [comment]
I'm still working on trying to replicate the issue with a test map.

The closest so far is the usual issue of not being able to see out of skybox brushes when inside it. This does suggest that the internal faces are being generated. This happens in DarkPlaces too, but "not" QuakeSpasm. So I'm wondering if it's something those two engines are doing.

![image](https://github.com/ericwa/ericw-tools/assets/424218/06594db5-188c-41f0-a6f6-191d97cf8ae2)

**Comment by hemebond** [comment]
Okay, it looks like this might just be caused by the poor geometry of the level I'm still rebuilding. Many of the structural walls are pyramids, a result of convert a .obj to a .map. This appears to be causing faces to not be culled and even VIS portals to include "outside" areas.

![image](https://github.com/ericwa/ericw-tools/assets/424218/9298b9fc-19e4-4d01-b8a9-d16d2c31e10d)
![image](https://github.com/ericwa/ericw-tools/assets/424218/fe6ff1ba-caf1-4832-b005-b3af1730c4b2)

**Comment by ericwa** [comment]
As far as engine differences, I just did a quick test with a 2 brush map:

[skytest.zip](https://github.com/ericwa/ericw-tools/files/11585472/skytest.zip)
![image](https://github.com/ericwa/ericw-tools/assets/239161/3185d29f-6a12-4dcf-89ee-c5034e8fbd03)

When noclipping into the sky:

- Quakespasm: can't see any sky faces
- tyrquake: can't see any sky faces (screen gets an underwater tint + water warp effect though)
- fte mar 1 2022: can't see any sky faces (screen gets a water warp effect though)
- darkplaces 2014 stable build: here, whenever the sky brush is on screen, the entire background (which is the gl_clear solid gray in other engines) is rendered as sky. Still, if I noclip inside where the sky brush is, I can still see the floor.

So, none of the engines I tested appear to be rendering the sky faces as 2-sided.

I'm still not sure if there is a tools bug that only manifests in more complex maps.

> Is it intentional for faces that touch sky brushes to not be culled by the compiler? I often add "skip" to any surface touching sky brushes to prevent this.

This is unintentional - the expected behaviour is that they're culled.

I just fixed a face merging bug in fa890456f608476940b5fdfa10585e1f4a83a118 which will hopefully help (the reported bug which prompted that fix was the opposite - a face which was partially covered by sky, and partially in the playable area of the map, was getting wrongly deleted. I think that commit will also fix cases where visible faces partially covered by sky were having the sky-covered part wrongly staying in the final .bsp.)

> I'm currently trying to compile using the brushbsp branch of the tools and it's even less forgiving of those thin brushes so I have a lot of leaks to fix.

Ok - `brushbsp` is now the main branch. If you get cases that look like false identifications of leaks feel free to report :)

**Comment by hemebond** [comment]
Latest *brushbsp* looks good, properly building the sky test map:
![image](https://github.com/ericwa/ericw-tools/assets/424218/cdc13f79-bd12-4058-b187-4cb6dd23e25e)

I also recompiled another map with it and it fixed the sky issue there (testing with FTEQW main branch build).

Before:
![image](https://github.com/ericwa/ericw-tools/assets/424218/b1ea5ef4-7364-40be-907f-8d89f85b5724)
After:
![image](https://github.com/ericwa/ericw-tools/assets/424218/893613bc-566f-4c37-a112-08816e096e2d)
