### ISSUE TITLE
Alpha textures don't cast shadows anymore on Alpha 2 release.

### ISSUE THREAD

**Issue by Return2Perdition** [ericwa/ericw-tools#384]
On Alpha 2 release textures with holes don't cast shadows anymore:

Alpha1: https://drive.google.com/file/d/1zQcemtsmP5zKLonHNRwkSGViXbUriHce/view?usp=sharing
Alpha2: https://drive.google.com/file/d/1GGhTvI_pjUPiJpbZbVOMkn3eMglo_Dki/view?usp=sharing

**Comment by ericwa** [comment]
Light tracing through fences still works with my test map, so I might have broken something subtle in alpha2.

Can you paste the fence brush as text here? Is this a texture included in the rerelease?

**Comment by Return2Perdition** [comment]
The texture is from a Half-Life classic retexture pack.

Brush:

; Brush 1438
; hanger:g[740] -> fence:g[46] -> cube:p[1]
 {
  ( -1650 692 -267 ) ( -1650 692 -275 ) ( -1538 692 -275 ) alpha/{GRATE4A [ 1.00000 0.00000 0.00000 27.00000 ]  [ 0.00000 0.00000 -1.00000 37.00000 ]  0  1.38000 1.00000 0 33558528 0
  ( -1538 692 -267 ) ( -1538 380 -267 ) ( -1650 380 -267 ) alpha/{GRATE4A [ 0.00000 -1.00000 0.00000 52.00000 ]  [ -1.00000 0.00000 0.00000 48.00000 ]  0  1.00000 1.12500 0 33558528 0
  ( -1538 692 -267 ) ( -1538 692 -275 ) ( -1538 380 -275 ) alpha/{GRATE4A [ 0.00000 1.00000 0.00000 53.00000 ]  [ 0.00000 0.00000 -1.00000 37.00000 ]  0  1.38000 1.00000 0 33558528 0
  ( -1650 380 -267 ) ( -1650 380 -275 ) ( -1650 692 -275 ) alpha/{GRATE4A [ 0.00000 -1.00000 0.00000 38.00000 ]  [ 0.00000 0.00000 -1.00000 37.00000 ]  0  1.38000 1.00000 0 33558528 0
  ( -1538 380 -267 ) ( -1538 380 -275 ) ( -1650 380 -275 ) alpha/{GRATE4A [ 0.00000 0.00000 -1.00000 21.00000 ]  [ -1.00000 0.00000 0.00000 62.00000 ]  0  1.00000 1.00000 0 33558528 0
  ( -1650 692 -275 ) ( -1650 380 -275 ) ( -1538 380 -275 ) alpha/{GRATE4A [ 0.00000 -1.00000 0.00000 11.00000 ]  [ 1.00000 0.00000 0.00000 22.00000 ]  0  1.38000 1.00000 0 33558528 0
 }

**Comment by ericwa** [comment]
Thanks, we tracked down what was going on here.

The 2.0.0-alpha1 build defaulted to `-emissivequality low`. alpha2 is stuck on `-emissivequality high` even if you request low. (The shadows are actually working in alpha2, they're just invisible because the surface light emission is coming from many different points.)

We'll fix that in the next alpha, but in this case when you want harsh shadows, it'd be better to turn off surface lighting from the blue glowing texture below the grate, and put a point light entity or two under there - that way you'll get the desired shadows even on a high quality lighting bake.

**Comment by Return2Perdition** [comment]
Okay, thanks. 2 point light entities don't work either.
I will try something different.

**Comment by ericwa** [comment]
They're definitely working in alpha6:

![image](https://github.com/ericwa/ericw-tools/assets/239161/d94af956-7871-48ec-b7c3-307954f3b189)

map: https://github.com/ericwa/ericw-tools/blob/brushbsp/testmaps/q2_light_translucency.map
