### ISSUE TITLE
Embree 4.3, problem building on Mac OS Sonoma (14.1.1) M2

### ISSUE THREAD

**Issue by victorbstan** [ericwa/ericw-tools#392]
The build process mostly works, except that the compatible installed embree is at version 4.3, and the "tools" build process doesn't seem to like that.

```
CMake Error at light/CMakeLists.txt:27 (FIND_PACKAGE):
  Could not find a configuration file for package "embree" that is compatible
  with requested version "3.0".

  The following configuration files were considered but not accepted:

    /opt/homebrew/opt/embree/lib/cmake/embree-4.3.0/embree-config.cmake, version: 4.3.0
    /opt/homebrew/lib/cmake/embree-4.3.0/embree-config.cmake, version: 4.3.0
```

**Comment by victorbstan** [comment]
PS. I have tried looking for a Version 3.x but can't find one for the latest Mac OS...

**Comment by ericwa** [comment]
We currently support 3.x only.

It would be possible to support both 3.x and 4.x with some `ifdef`'s - https://github.com/embree/embree#upgrading-from-embree-3-to-embree-4 ; I don't want to require 4.x yet though, because it's not packaged everywhere. e.g. vcpkg only has embree3.

You could try installing embree3 through vcpkg if you want:

https://vcpkg.io/en/getting-started.html

You'd do `vcpkg install embree3` (it's a fairly slow compile) then include the `-DCMAKE_TOOLCHAIN_FILE=[path to vcpkg]/scripts/buildsystems/vcpkg.cmake` when running cmake to configure ericw-tools

**Comment by ericwa** [comment]
I added embree4 support in db0951d
